### ISSUE TITLE
[회원가입] Request, Response 모델 설계

### ISSUE THREAD

**Issue by mankicho** [Laundry-Platform/Laundry_Core#50]
**Problem or enhancements and It's Background**
- 빠른 API 문서작성을위해 요청, 응답 모델 설계

**Solutions**
- 위 내용에 대한 해결책에 대해 설명해주세요.

**TODO Tasks and Cautions**
- [ ] 회원가입 view 보고 필요한 데이터 잘 설계하기

**Additional context**

**Comment by Dokyeongyun** [comment]
@dldmldlsy @newisdom79 
- #63 이슈로 내용 이동되었습니다.
