### ISSUE TITLE
[인증] 회원가입 시 핸드폰번호 인증하기 휴대폰 번호 인증 방법 조사

### ISSUE THREAD

**Issue by mankicho** [Laundry-Platform/Laundry_Core#55]
**Problem or enhancements and It's Background**
- 회원가입 데이터에 핸드폰번호 필드가있는데, 어떻게 인증할지 생각해보기

**Solutions**
- 서드파티 솔루션 사용하는것이 좋아보임 (대표적으로 네이버 메세징 API??)

**TODO Tasks and Cautions**
- [ ] 외부 API 에 의존하는 테스트코드는 어떻게 짤 수 있을지 고민해보기 (테스트 작성까지하면 더 좋음)

**Additional context**

**Comment by Dokyeongyun** [comment]
@dldmldlsy @newisdom79 
- 새로운 이슈로 등록했습니다.
